dev to master
JodyLS27/rapid-recharge pull request #1
Opened 2023-01-23 14:23 UTC by JodyLS27

Pulling base setup from dev to master.

2023-01-23 14:31 UTC, swagween commented on src/main.cpp
> +	player.set_shape(window_size, { 25.0f, 25.0f });
you could consider making the shape size a member variable of the Player (e.g., `m_width` and `m_height`), and just set those parameters upon player initialization

2023-01-23 14:34 UTC, swagween commented on src/player.hpp
> +		sf::RectangleShape get_shape();
this should return a reference to the shape, as this will create a copy of the player's shape each time it's called (which is every frame)

2023-01-23 14:38 UTC, swagween commented on src/player.hpp
> +		void set_shape(sf::Vector2u window_size, sf::Vector2f shape_size, sf::Color color = sf::Color::Red);
why initialize the color here in the function declaration? I'm not sure what will happen if this function is called with a different color

2023-01-23 14:41 UTC, JodyLS27 commented on src/main.cpp
> +	player.set_shape(window_size, { 25.0f, 25.0f });
Good idea, will implement this, thank you.

2023-01-23 14:42 UTC, swagween commented on src/player.cpp
> +		update_position(m_direction, delta_time);
I wouldn't do this here. it isn't obvious that a function called `set_direction` will also update the player's position. maybe consider putting this in a separate `update()` or `logic()` member function, and call that separately in main after event polling is complete

2023-01-23 14:42 UTC, JodyLS27 commented on src/player.hpp
> +		sf::RectangleShape get_shape();
Out, Yea Wi

> this should return a reference to the shape, as this will create a copy of the player's shape each time it's called (which is every frame)

Out, yea will fix this, thank you.

2023-01-23 14:45 UTC, aleokdev commented on src/player.hpp
> +		void set_shape(sf::Vector2u window_size, sf::Vector2f shape_size, sf::Color color = sf::Color::Red);
That's just assigning a default value for the parameter, it's not initializing anything. If the function is called without the color parameter it will use Red as a default. You can of course override it by using the color parameter normally.

2023-01-23 14:46 UTC, swagween commented on src/player.cpp
> +	void Player::set_shape(sf::Vector2u window_size, sf::Vector2f shape_size, sf::Color color)
feels weird to have `window_size` in this function's parameter list. The player shouldn't know about the size of the window. consider just changing this to `position`, and then just pass `window_size * 0.5f` from main instead

2023-01-23 14:46 UTC, JodyLS27 commented on src/player.hpp
> +		void set_shape(sf::Vector2u window_size, sf::Vector2f shape_size, sf::Color color = sf::Color::Red);
This is a default function value. If I pass in say green, it will change 😄 
Just testing some things in c++ 😁

2023-01-23 14:47 UTC, swagween commented on src/player.cpp
> +		m_position = m_shape.getPosition();
if you make the above change, then here you can just say `m_position = position` instead of doing an unnecessary call to `getPosition()`

2023-01-23 14:48 UTC, JodyLS27 commented on src/player.cpp
> +		update_position(m_direction, delta_time);
Great Idea... Stick to good coding practise.

2023-01-23 14:48 UTC, swagween commented on src/player.hpp
> +	class Player
i don't think you should indent after a namespace

2023-01-23 14:51 UTC, swagween commented on src/player.cpp
> +#include <player.hpp>
shouldn't this be `"player.hpp"` instead of `<player.hpp>`? I would expect this to give you a compiler error..

2023-01-23 14:54 UTC, swagween commented on src/player.cpp
> +		: m_score(0), m_speed(10)
you should set the player's speed using some `set_speed()` member function. or, you can initialize it when the player instance is initialized in main. so here you would write something like `Player(int score, int speed) : m_score(score), m_speed(speed)`, and then when you declare the player in main you would write `Player player = Player(0, 10);`

2023-01-23 16:39 UTC, Kouros26 requested changes

2023-01-23 16:39 UTC, Kouros26 commented on src/player.cpp
> +	void Player::update_position(sf::Vector2i direction, float delta_time)
you should use references when you pass a structure or class as a parameter as it will move the value instead of creating a copy (here for example it would be a sf::Vector2i& direction)

2023-01-23 18:13 UTC, aleokdev commented on src/player.cpp
> +	void Player::update_position(sf::Vector2i direction, float delta_time)
No, this is definitely okay. A vector2i is only 8 bytes long, it's OK to copy it (using a ref here would probably optimize to a copy anyway i think)

2023-01-23 18:14 UTC, aleokdev commented on src/player.cpp
> +#include <player.hpp>
It only changes include location search preference.

2023-01-23 19:21 UTC, karnkaul commented on src/player.cpp
> +#include <player.hpp>
Prefer `<>` to `""` in includes

2023-01-23 19:21 UTC, karnkaul commented on src/player.cpp
> +namespace player
You don't want a namespace per class.

2023-01-24 00:59 UTC, karnkaul commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.20)
3.20 is too high, why?

2023-01-24 01:00 UTC, karnkaul commented on CMakeLists.txt
> +target_sources(${PROJECT_NAME} PRIVATE src/main.cpp "src/player.cpp")
Add headers to target sources too

2023-01-24 01:00 UTC, karnkaul commented on src/player.hpp
> +	class Player
+1
Use clang format to auto format code

2023-01-24 01:02 UTC, karnkaul commented on src/player.hpp
> +		void update_position(sf::Vector2i direction, float delta_time);
I like the fact that you're thinking of types to enforce quantized values instead of floats etc, but here you might want to instead pass a "pseudo vector", aka a unit vector that represents a direction (is a point on a unit circle about the origin). So `sf::Vector2f`.

2023-01-24 01:03 UTC, karnkaul commented on src/player.hpp
> +		sf::RectangleShape get_shape();
You'll also need const qualified overloads:
```cpp
sf::RectangleShape& get_shape();
sf::RectangleShape const& get_shape() const;
```

2023-01-24 04:10 UTC, JodyLS27 commented on src/player.cpp
> +	void Player::update_position(sf::Vector2i direction, float delta_time)
I stuck with a Copy as I was not altering the value to return and use it.
But yea, I might need to understand references better 🤔

2023-01-24 04:12 UTC, JodyLS27 commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.20)
No reason to be honest. 
I can drop down to 3.18.

2023-01-25 09:15 UTC, closed without merging