Menu Manager base system
JodyLS27/rapid-recharge pull request #5
Opened 2024-02-20 17:42 UTC by JodyLS27

# Info
This is a base system for the menus in the game so that one menu at a time is loaded into memory.
There are two base classes `i_switch_menu` and `i_menu`. There are also, two menu classes for now, `main_menu` and `settings_menu` and the `menu_manager` is used to manage which menu is currently loaded by controlling the switching and the calling from the `game_manager`.

2024-02-24 13:07 UTC, Kouros26 requested changes

2024-02-24 13:07 UTC, Kouros26 commented on include/core/menu_manager.hpp
> +	class MenuManager : public menu::ISwitchMenu
you don't need to write ```menu::ISwitchMenu``` since you're in the ```menu``` namespace.

2024-02-24 13:07 UTC, Kouros26 commented on src/core/game_manager.cpp
> +	menu_manager.init();
you should call this in the ```game_manager::init()``` function

2024-02-24 13:07 UTC, Kouros26 commented on src/menu/main_menu.cpp
> +			menu_manager.switch_menu(std::make_unique<menu::SettingsMenu>());
this logic should be in the menu manager not in one of the menus

2024-02-24 13:07 UTC, Kouros26 commented on src/menu/settings_menu.cpp
> +			menu_manager.switch_menu(std::make_unique<menu::MainMenu>());
same here

2024-02-24 13:09 UTC, Kouros26 commented
Also forgot to add that your ```IMenu``` class shouldn't know about the ```MenuManager``` class

2024-02-24 13:28 UTC, JodyLS27 commented on src/menu/main_menu.cpp
> +			menu_manager.switch_menu(std::make_unique<menu::SettingsMenu>());
Thanks @Kouros26, Should this rather be in the `menu_manager::update()` function and if we are not switching, we are running the current Menus `update()` ?

2024-02-24 13:38 UTC, Kouros26 commented on src/menu/main_menu.cpp
> +			menu_manager.switch_menu(std::make_unique<menu::SettingsMenu>());
yep exactly, but no need to check if we are switching or not, run the current menu's update function regardless

2024-03-06 13:07 UTC, JodyLS27 commented on src/core/game_manager.cpp
> +	menu_manager.init();
✅ Implemented.

2024-03-06 13:14 UTC, JodyLS27 commented on src/menu/main_menu.cpp
> +			menu_manager.switch_menu(std::make_unique<menu::SettingsMenu>());
I am going to look into this.
From my understanding of a state machine, we want this in each menu class as each one can switch to different classes based on the logic Constraint.

_(i.e: `Main Menu` can switch to `Settings`, `Game` and `Top Score` But Settings can only go back to `Main Menu` and cannot go to `Game`)_
So placing this logic in each State (`Sub Class`) should be better ?

2024-03-06 13:15 UTC, JodyLS27 commented
> Also forgot to add that your `IMenu` class shouldn't know about the `MenuManager` class

yes, Will Implement this now, Thanks man.

2025-10-07 17:40 UTC, closed without merging